# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b22df0e7e48c3a1d0d4d81f9aac50f86834ca68777c94e14075928edac3b2bda7d5e9654722ea017f1df869996ca073d5dc7074444cfcd64a79243ff7c4aa71f

test:
  secret_key_base: 785e305917edd8391e239a80da3a7b7f1f1e98f075a5ea832f565287cdc883fbfe8410836f64d00698069fd6eedf18574f7e9691a43c726ae0fc38707f578373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
